projects:
  1mil:
    schemaPath: graphql/schema.graphql
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: graphql/API.ts
        docsFilePath: graphql
        region: us-east-2
        apiId: null
extensions:
  amplify:
    version: 3
